### ISSUE TITLE
Сайт перестал работать

### ISSUE THREAD

**Issue by snoward** [AndreyAkinshin/ProblemBook.NET#11]
Не получается зайти на сайт уже в течение недели. 
Скачал pdf, но онлайн всё-таки было удобнее.

<img width="589" alt="2" src="https://cloud.githubusercontent.com/assets/8896921/23401050/1970144a-fdc8-11e6-9387-0a707ff2fdd0.png">

**Comment by AndreyAkinshin** [comment]
Спасибо за багрепорт. Посмотрю что с этим можно сделать.

**Comment by AndreyAkinshin** [comment]
@snoward,  сейчас всё должно работать.

**Comment by kirillmyp** [comment]
Привет
Приметил что сайт не открывается
PDF выкачиваются

**Comment by AndreyAkinshin** [comment]
@kirillmyp спасибо за информацию, gitbook опять обновляли свою инфраструктуру.
Прямо сейчас сайт доступен вот по этому адресу: https://andreyakinshin.gitbook.io/problembookdotnet/
Починка домена problembook.net в процессе.

**Comment by kirillmyp** [comment]
Привет
Кажется сервак ломанули

https://andreyakinshin.gitbook.io/problembookdotnet/

http://problembook.net/content/ru/INTRODUCTION.html
http://problembook.net/content/en/INTRODUCTION.html

![изображение](https://user-images.githubusercontent.com/7809503/100222836-b9121000-2f2b-11eb-8f58-20afb1840e12.png)

**Comment by AndreyAkinshin** [comment]
@kirillmyp я в какой-то момент не стал продливать владение доменом problembook.net, его перекупили какие-то другие ребята. Актуальная ссылка на веб-версию: https://andreyakinshin.gitbook.io/problembookdotnet/
Я старался убрать ссылки на problembook.net из всех мест, но мог где-то проглядеть. Если такие ссылки ещё существуют, то дайте знать, где вы их нашли — я уберу.
