### ISSUE TITLE
Ссылка на online версию ведёт к ошибке

### ISSUE THREAD

**Issue by PeskovV** [AndreyAkinshin/ProblemBook.NET#13]
Вероятно ссылка на online версию битая: https://www.problembook.net/content/en/INTRODUCTION.html
![изображение](https://user-images.githubusercontent.com/26106827/65944383-3d592800-e43a-11e9-8e64-789201d74860.png)

**Comment by ComeWithMe** [comment]
![image](https://user-images.githubusercontent.com/11459882/100624915-01b73800-3335-11eb-9d6d-b2a0d6c6a511.png)
Уже даже редиректит на сомнительный сайт.

**Comment by vvvvvvch** [comment]
Ссылки на чтение обновились.

https://andreyakinshin.gitbook.io/problembookdotnet/ru/introduction
https://andreyakinshin.gitbook.io/problembookdotnet/en/introduction

Почитайте этот коммент https://github.com/AndreyAkinshin/ProblemBook.NET/issues/11#issuecomment-733660938

**Comment by chesh111re** [comment]
@chudovsky Спасибо за информацию! Закрываю issue
