### ISSUE TITLE
OverloadResolutionBasic-S: Error in one of the solutions?

### ISSUE THREAD

**Issue by cubrr** [AndreyAkinshin/ProblemBook.NET#6]
Currently, the [explanation](https://github.com/AndreyAkinshin/ProblemBook.NET/blob/af278f36c76c121efbbb79b3d7ae568bbb0113dc/en/Oop/OverloadResolutionBasic-S.md) says:

> - `Foo(new Bar(), new Bar())` -> `params T[]`

> The `object, object` option is inaccessible because of number of arguments.

Perhaps I'm missing something here, but I think this might be incorrect, since `new Bar(), new Bar()` is two objects and thus the `object, object` overload *would* be accessible.

**Comment by AndreyAkinshin** [comment]
Thanks!
